version: '3.9'

networks:
  dev_networks:

services:

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: netology_flask
      POSTGRES_PASSWORD: netology
      POSTGRES_DB: db_postgres